#!/bin/bash
set -e

# ── Config ────────────────────────────────────────────────────────────────────
REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
TASK_FILE=$1
BRANCH="feature/$(date +%s)"

if [ -z "$TASK_FILE" ]; then
  echo "Usage: ./orchestrate.sh path/to/task.md"
  exit 1
fi

if [ ! -f "$TASK_FILE" ]; then
  echo "Task file not found: $TASK_FILE"
  exit 1
fi

TASK_TITLE=$(head -1 "$TASK_FILE" | sed 's/# //')

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Scene Orchestrator"
echo "   Task: $TASK_TITLE"
echo "   Branch: $BRANCH"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Step 1: Dev Agent ─────────────────────────────────────────────────────────
echo ""
echo "⚙️  [1/4] Running dev agent..."
cd "$REPO_ROOT"
git checkout -b "$BRANCH"

claude --print "
You are acting as the engineering-backend-architect agent for Scene.
Read the task below and implement it fully.
Follow all conventions in CLAUDE.md.
Query OpenViking at http://localhost:1933 for codebase context before starting.
Commit your changes with a clear message when done.
Do not open a PR — the orchestrator will handle that.

TASK:
$(cat "$TASK_FILE")
"
# Commit whatever the agent wrote
cd "$REPO_ROOT"
git add -A
if git diff --staged --quiet; then
  echo "⚠️  No changes to commit — check agent output"
  exit 1
fi
git commit -m "feat: $TASK_TITLE"

echo "✓ Dev agent complete"

# ── Step 2: Run PromptFoo ─────────────────────────────────────────────────────
echo ""
echo "🧪 [2/4] Running PromptFoo evals..."
cd "$REPO_ROOT/backend"
promptfoo eval --no-cache 2>&1 | tail -5
echo "✓ Evals complete"

# ── Step 3: Open PR ───────────────────────────────────────────────────────────
echo ""
echo "📬 [3/4] Opening PR..."
cd "$REPO_ROOT"
git push origin "$BRANCH"

PR_URL=$(gh pr create \
  --title "$TASK_TITLE" \
  --body "Auto-generated by Scene Orchestrator from $TASK_FILE" \
  --base main)

PR_NUM=$(gh pr view "$BRANCH" --json number -q .number)
echo "✓ PR #$PR_NUM opened: $PR_URL"

# ── Step 4: Review Agent ──────────────────────────────────────────────────────
echo ""
echo "🔍 [4/4] Running review agent..."
git diff main.."$BRANCH" > /tmp/scene_diff.txt

REVIEW=$(claude --print "
You are acting as the engineering-code-reviewer and engineering-security-engineer 
agents for Scene, a React Native / Node.js / Express / PostgreSQL app.

Review this PR diff and output a structured report with exactly this format:

## Review: $TASK_TITLE

### CRITICAL
- (bugs or security issues that must be fixed before merge)

### WARNING  
- (things that should be addressed soon)

### SUGGESTION
- (optional improvements)

### VERDICT
APPROVE / REQUEST CHANGES

Be terse. Flag real issues only. No filler.

DIFF:
$(cat /tmp/scene_diff.txt)
")

# Post review as PR comment
echo "$REVIEW" | gh pr comment "$PR_NUM" --body-file -

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Done. Review posted to PR #$PR_NUM"
echo "   $PR_URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Cleanup
rm -f /tmp/scene_diff.txt
cd "$REPO_ROOT"
git checkout main