#!/bin/bash
set -euo pipefail

# ── Validate task file ────────────────────────────────────────────────────────
if [ -z "${1:-}" ]; then
  echo "Usage: ./orchestrate.sh tasks/your-task.md"
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
TASK_FILE="$(realpath "$1")"
TASKS_DIR="$(realpath "$REPO_ROOT/tasks")"

if [[ "$TASK_FILE" != "$TASKS_DIR"/* ]]; then
  echo "Error: task file must be inside the tasks/ directory"
  exit 1
fi

if [ ! -f "$TASK_FILE" ]; then
  echo "Error: task file not found: $TASK_FILE"
  exit 1
fi

# ── Config ────────────────────────────────────────────────────────────────────
TASK_TITLE=$(head -1 "$TASK_FILE" | sed 's/^#[[:space:]]*//')
DIFF_FILE=$(mktemp)
trap 'rm -f "$DIFF_FILE"' EXIT

# ── Branch setup (skip if already on a feature branch) ───────────────────────
cd "$REPO_ROOT"
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ "$CURRENT_BRANCH" == "main" ]] || [[ "$CURRENT_BRANCH" == "master" ]]; then
  BRANCH="feature/$(date +%s)"
  git checkout -b "$BRANCH"
  echo "ℹ️  Created branch: $BRANCH"
else
  BRANCH="$CURRENT_BRANCH"
  echo "ℹ️  Already on branch: $BRANCH — skipping branch creation"
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 Scene Orchestrator"
echo "   Task: $TASK_TITLE"
echo "   Branch: $BRANCH"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Step 1: Dev Agent ─────────────────────────────────────────────────────────
echo ""
echo "⚙️  [1/4] Running dev agent..."

COMMIT_BEFORE=$(git rev-parse HEAD)

# --print makes claude non-interactive: it processes the prompt fully, outputs
# to stdout, and exits — so the script reliably waits for completion.
claude --dangerously-skip-permissions --print "
You are acting as the engineering-backend-architect agent for Scene.
Read the task below and implement it fully.
Follow all conventions in CLAUDE.md.
Query OpenViking at http://localhost:1933 for codebase context before starting.
Commit your changes with a clear message when done.
Do not open a PR — the orchestrator will handle that.

SCOPE CONSTRAINT — CRITICAL:
- Only write or edit files inside backend/src/ and frontend/
- Never touch .claude/, settings.json, CLAUDE.md, orchestrate.sh, or any config/tooling file
- Never request permission changes or modify tool settings — just implement the task

TASK:
$(cat "$TASK_FILE")
"

# ── Capture commit ────────────────────────────────────────────────────────────
cd "$REPO_ROOT"
COMMIT_AFTER=$(git rev-parse HEAD)

if [ "$COMMIT_BEFORE" != "$COMMIT_AFTER" ]; then
  # Agent committed — nothing more to do
  echo "✓ Agent committed: $(git log -1 --oneline)"
else
  # Agent wrote files but didn't commit — stage source dirs and commit
  git add backend/src/ frontend/ 2>/dev/null || true

  if git diff --staged --quiet; then
    echo "⚠️  No changes detected — agent may not have written files"
    echo "   Check agent output above and apply changes manually"
    if [[ "$CURRENT_BRANCH" == "main" ]] || [[ "$CURRENT_BRANCH" == "master" ]]; then
      git checkout main
      git branch -D "$BRANCH"
    fi
    exit 1
  fi

  git commit -m "feat: ${TASK_TITLE}"
  echo "✓ Staged changes committed: $(git log -1 --oneline)"
fi

echo "✓ Dev agent complete"

# ── Step 2: PromptFoo Evals ───────────────────────────────────────────────────
echo ""
echo "🧪 [2/4] Running PromptFoo evals..."
if cd "$REPO_ROOT/backend" && promptfoo eval --no-cache -c "$REPO_ROOT/backend/promptfooconfig.yaml" 2>&1 | tee /tmp/eval_out.txt | tail -5; then
  echo "✓ Evals complete"
else
  echo "⚠️  Evals failed — review /tmp/eval_out.txt before merging"
fi

# ── Step 3: Open PR ───────────────────────────────────────────────────────────
echo ""
echo "📬 [3/4] Opening PR..."
cd "$REPO_ROOT"
git push origin "$BRANCH"

PR_URL=$(gh pr create \
  --title "$TASK_TITLE" \
  --body "$(printf 'Auto-generated by Scene Orchestrator\n\nTask file: %s' "$TASK_FILE")" \
  --base main)

PR_NUM=$(gh pr view "$BRANCH" --json number -q .number)
echo "✓ PR #$PR_NUM opened: $PR_URL"

# ── Step 4: Review Agent ──────────────────────────────────────────────────────
echo ""
echo "🔍 [4/4] Running review agent..."
git diff main.."$BRANCH" > "$DIFF_FILE"

if [ ! -s "$DIFF_FILE" ]; then
  echo "⚠️  Empty diff — nothing to review"
  exit 1
fi

REVIEW=$(claude --print "
You are acting as the engineering-code-reviewer and engineering-security-engineer
agents for Scene, a React Native / Node.js / Express / PostgreSQL app.

Review this PR diff and output a structured report with exactly this format:

## Review: $TASK_TITLE

### CRITICAL
- (bugs or security issues that must be fixed before merge)

### WARNING
- (things that should be addressed soon)

### SUGGESTION
- (optional improvements)

### VERDICT
APPROVE / REQUEST CHANGES

Be terse. Flag real issues only. No filler.

DIFF:
$(cat "$DIFF_FILE")
")

echo "$REVIEW" | gh pr comment "$PR_NUM" --body-file -

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Done. Review posted to PR #$PR_NUM"
echo "   $PR_URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

cd "$REPO_ROOT"
if [[ "$CURRENT_BRANCH" != "main" ]] && [[ "$CURRENT_BRANCH" != "master" ]]; then
  : # stay on the feature branch — caller may want to inspect it
else
  git checkout main
fi
